version: "3"
services:
  api-solid-pg:
    container_name: api-solid-pg
    restart: always
    image: bitnami/postgresql:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api_solid_db
    networks:
      - api-solid-network
